package CompetitiveProgrammingQuestions.dynamicProgramming2;

import java.util.Scanner;
/*
* Balika Vadhu- Problem
Send Feedback
Anandi and Jagya were getting married again when they have achieved proper age. Dadi Sa invited Alok Nath to do the kanyadaan and give blessings. Alok Nath has 2 blessings. Each bessing is in the form of a string consisting of lowercase charaters(a-z) only. But he can give only one blessing of K length because some priest told him to do so. Thus he decides to generate a blessing using the other two blessings. While doing this he wants to ensure that happiness brought into their life by his blessing is maximum.
The generated blessing is a common subsequence of length K of the two blessings he has. Happiness of the blessing he generates is calculated by the sum of ASCII values of characters in the blessing and he wants the happiness to be maximum. If he is not able to generate a common subsequence of length K then the happiness is 0 (zero). Alok Nath comes to you and asks you to find the maximum happiness that can be generated by the two blessings he has.
Input Specification
First line consists of number of test cases t. Each test case consists of two strings b1 (blessing 1),b2 (blessing 2) and an integer K, each of them in separate lines.
Output Specification
Output consists of t lines each containing an integer denoting the maximum happiness value that can be generated by the two blessings.
Constraint
1 <= t <= 50

1 <= length(b1) , length(b2) <= 100

1 <= K <= 100
Sample Input
2
asdf
asdf
3
anandi
jagya
3
Sample Output
317
0*/
public class BalikaVadhu {
    public static void main(String[] args) {
        Scanner sc  = new Scanner(System.in);
        int t = Integer.parseInt(sc.nextLine());
        String s1[] = new String[t];
        String s2[] = new String[t];
        int k[] = new int[t];
        for(int i=0;i<t;i++) {

            s1[i] = sc.nextLine();
            s2[i] = sc.nextLine();
            k[i] = Integer.parseInt(sc.nextLine());
        }
        for(int i=0;i<t;i++) {

            int m = s1[i].length();
            int n = s2[i].length();
            int dp[][][] = new int[m + 1][n + 1][k[i] + 1];
            for (int ii = 0; ii <= m; ii++) {
                for (int j = 0; j <= n; j++) {
                    for (int h = 1; h <= k[i]; h++) {
                        dp[ii][j][h] = -1;
                    }
                }
            }
            System.out.println(maxHappiness(s1[i], m, s2[i], n, k[i], dp));
           /* for(int ii =0;ii<=k[i];ii++) {
                System.out.println("k = "+ii);
                print(dp, m, n, ii);
            }*/
        }
    }

    private static int maxHappiness(String s1, int m, String s2, int n, int k, int[][][] dp) {
        if(m<= 0 || n<=0 || k<=0){
            return 0;
        }
        if (m < k || n < k)
        {
            return 0;
        }
        if(dp[m][n][k] > -1){
            return dp[m][n][k];
        }
        if(s1.charAt(m-1) == s2.charAt(n-1)){
            //i can take it in my k length of CS or not
            dp[m][n][k]= Math.max(s1.charAt(m-1)+ maxHappiness(s1,m-1,s2,n-1,k-1,dp),
                                Math.max(maxHappiness(s1,m-1,s2,n,k,dp),
                            maxHappiness(s1,m,s2,n-1,k,dp)));
        }else{
            dp[m][n][k]=  Math.max(maxHappiness(s1,m-1,s2,n,k,dp),
                    maxHappiness(s1,m,s2,n-1,k,dp));
        }

        return dp[m][n][k] <= 122*k && dp[m][n][k] >= 97*k ?  dp[m][n][k] : 0;

    }

    private static void print(int[][][] dp, int m, int n, int k) {
        for (int i =0;i<=m;i++){
            for(int j =0;j<=n;j++){
                System.out.print(dp[i][j][k]+" ");
            }
            System.out.println();
        }
    }
}


